### ISSUE TITLE
LSP does not find the "Content-Length" for psalm-language-server

### ISSUE THREAD

**Issue by merlindiavova** [pragtical/lsp#1]
The pattern `Content%-Length:%s*(%d+)` works well for most LS's however, the `psalm-language-server` returns response in the following format

```
{"jsonrpc":"2.0","method":"window\/logMessage","params":{"type":3,"message":"Initializing: Loading Reference Cache..."}}
Content-Type: application/vscode-jsonrpc; charset=utf8
Content-Length: 115
```

The current pattern does not match the Content-Length and therefore fails to init the LS.

As a quick workaround I'm modified line `1202` to 
```lua
if output:find('^Content%-Length: %d+\r\n') or output:find('Content%-Length:%s*(%d+)') then
```

**Comment by jgmdev** [comment]
Can you share the config used to activate psalm?

**Comment by merlindiavova** [comment]
Sure, see below

```lua
lsp.add_server {
  name = "psalmls",
  language = "php",
  file_patterns = {
    "%.php$",
  },
  command = {
    core.root_project():absolute_path("vendor/bin/psalm-language-server"),
    '--config', core.root_project():absolute_path("psalm.xml"),
    },
  incremental_changes = true,
  verbose = false
}

```

**Comment by jgmdev** [comment]
Finally tested this and as you shared above just removing the `^` fixed the issue but it seems that psalm has some issues with my installed PHP version (8.2.12) and I keep getting the following when typing on the document:

```
[psalm-language-server] RuntimeException: PHP Error: Undefined property: stdClass::$range in vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/Server/TextDocument.php:122 for command with CLI args "vendor/bin/psalm-language-server --config psalm.xml" in vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:77
```

Now that PHP removed or deprecated dynamic properties it has become a nightmare for code that depended on that :S

Anyway fixed it with:

```diff
-        if (count($contentChanges) === 1 && isset($contentChanges[0]) && $contentChanges[0]->range === null) {
+        if (count($contentChanges) === 1 && isset($contentChanges[0]) && (!property_exists($contentChanges[0], "range") || $contentChanges[0]->range === null)) {
```

But I'm not getting any autocompletion or diagnostics as far as I see, maybe I need to configure something on the `psalm.xml` file
