### ISSUE TITLE
Marksman LSP

### ISSUE THREAD

**Issue by k8ieone** [pragtical/lsp#11]
There's an LSP server for Markdown called [Marksman](https://github.com/artempyanykh/marksman) offering some additional Markdown features. There's no other server for Markdown defined in the default configuration. Is it worthy enough to add? :smile:

**Comment by jgmdev** [comment]
Done, thanks for letting me know about this language server. Is nice to finally have a table of content for quick navigation :D

![marksman-symbols-tree](https://github.com/user-attachments/assets/70e56816-3647-4842-a8a5-f6432663d416)
